### ISSUE TITLE
А где ответы на теоретические вопросы 1 и 2 задания?

### ISSUE THREAD

**Issue by Inonecloud** [Annoying220/Java_Course#1]
https://github.com/Annoying220/Java_Course/blob/9c402be0a277bd8763a485db03c4740ecdf57f97/lesson1/task1/src/Task1.java#L2

**Comment by Annoying220** [comment]
task1.txt и task2.txt лежат в репозитории Java_Course

**Comment by Inonecloud** [comment]
Ok
